version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Prepare the Workspace
          command: |
                  mkdir -p ~/ros2_rpi/ros2_ws/src ~/ros2_rpi/rpi-root
                  sh -c 'while fuser /var/lib/apt/lists/lock >/dev/null 2>&1 ; do echo -en "\rWaiting for other software managers to finish..."; sleep 0.5; done'
                  sudo apt-get --allow-unauthenticated update
                  sudo apt-get install -y qemu-user-static python3-requests python3 python3-pip libparted-dev build-essential
                  sudo python3 -m pip install -U pyparted
      - run:
          name: Build the crosscompile docker
          command: |
                cd /home/circleci/project
                docker pull avrabe/ros2-raspbian_crosscompiler:latest
                docker build --cache-from avrabe/ros2-raspbian_crosscompiler -f Dockerfile.bootstrap -t  ros2-raspbian:crosscompiler .
      - run:
          name: Prepare the raspbian image
          command: |
                cd /home/circleci/project
                ./convert_raspbian_docker.py ros2-raspbian
                ./export_raspbian_image.py ros2-raspbian:lite ros2_dependencies.bash ros2-raspbian-rootfs.tar
                sudo tar -C ~/ros2_rpi/rpi-root -xf ros2-raspbian-rootfs.tar
      - run:
          name: Checkout ROS2
          command: |
                echo polly
                git clone https://github.com/avrabe/polly.git ~/ros2_rpi/polly
                echo wget
                wget https://raw.githubusercontent.com/ros2/ros2/crystal/ros2.repos -o ~/ros2_rpi/ros2_ws/ros2.repos
                echo checkout
                docker run -it --rm -v ~/ros2_rpi/polly:/polly -v ~/ros2_rpi/ros2_ws:/ros2_ws -v /home/circleci/project/vcs_ros2.bash:/vcs_ros2.bash -v ~/ros2_rpi/rpi-root:/raspbian_ros2_root -w /ros2_ws  ros2-raspbian:crosscompiler  bash /vcs_ros2.bash
      - run:
          name: build ROS2
          command: |
                docker run -it --rm -v ~/ros2_rpi/polly:/polly -v ~/ros2_rpi/ros2_ws:/ros2_ws -v /home/circleci/project/build_ros2.bash:/build_ros2.bash -v ~/ros2_rpi/rpi-root:/raspbian_ros2_root -w /ros2_ws  ros2-raspbian:crosscompiler  bash /build_ros2.bash
