version: 2
jobs:
  build:
    machine: True

    steps:
      - checkout
      - run:
          name: Greeting
          command: |
                  sudo apt-get --allow-unauthenticated update
                  sudo apt-get install -y qemu-user-static python3-parted python3-requests
                  mkdir -p ~/ros2_rpi/ros2_ws/src ~/ros2_rpi/ros2_raspbian_tools ~/ros2_rpi/rpi-root
                  cd ~/ros2_rpi/ros2_ws
                  wget https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
                  cd ~/ros2_rpi
                  git clone https://github.com/avrabe/polly.git
                  cp $CIRCLE_WORKING_DIRECTORY/*.py $CIRCLE_WORKING_DIRECTORY/*.bootstrap $CIRCLE_WORKING_DIRECTORY/*.txt $CIRCLE_WORKING_DIRECTORY/*.bash ~/ros2_rpi/ros2_raspbian_tools
      - run:
          name: Print the Current Time
          command: |
                cd $CIRCLE_WORKING_DIRECTORY/
                docker pull avrabe/ros2-raspbian_crosscompiler:latest
                docker build --cache-from avrabe/ros2-raspbian_crosscompiler -f Dockerfile.bootstrap -t  ros2-raspbian:crosscompiler .
                cd ~/ros2_rpi/ros2_raspbian_tools
                ./convert_raspbian_docker.py ros2-raspbian
                ./convert_raspbian_docker.py -i raspbian_lite_latest ros2-raspbian
                ./export_raspbian_image.py ros2-raspbian:lite ros2_dependencies.bash ros2-raspbian-rootfs.tar
                sudo tar -C ~/ros2_rpi/rpi-root -xf ros2-raspbian-rootfs.tar
                docker run -it --rm -v ~/ros2_rpi/polly:/polly -v ~/ros2_rpi/ros2_ws:/ros2_ws -v ~/ros2_rpi/ros2_raspbian_tools/vcs_ros2.bash:/vcs_ros2.bash -v ~/ros2_rpi/rpi-root:/raspbian_ros2_root -w /ros2_ws  ros2-raspbian:crosscompiler  bash /vcs_ros2.bash
                docker run -it --rm -v ~/ros2_rpi/polly:/polly -v ~/ros2_rpi/ros2_ws:/ros2_ws -v ~/ros2_rpi/ros2_raspbian_tools/build_ros2.bash:/build_ros2.bash -v ~/ros2_rpi/rpi-root:/raspbian_ros2_root -w /ros2_ws  ros2-raspbian:crosscompiler  bash /build_ros2.bash

